services:
  app:
    image: itzcrazykns1337/perplexica:main
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      - SEARXNG_API_URL=${SEARXNG_API_URL}
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./perplexica/backend-dbstore:/home/perplexica/data
      - ./perplexica/uploads:/home/perplexica/uploads
      - ./perplexica/config.toml:/home/perplexica/config.toml:rw
    restart: unless-stopped
